#!/bin/sh
#
# Author: DooMLoRD@XDA
#
# Script to extract and search for required address for perf_event exploit
#
# Usage:
#  extract_address_and_disassemble zImage
#
# Output:
#  addresses.txt - this will contain the 5 crucial addresses from the kallsyms
#  kernel.dasm   - this will contain the disassembelled kernel
#

# Update path to toolchain
echo "Searching for zImage compression"

declare -a comp_list=("xz" "lzop" "lz4" "gzip")
declare -a comp_pt_list=("\xfd7zXZ\x00" "\x89LZO\x00" "\x02\x21\x4c\x18" "\x1f\x8b\x08")

unpack_cmd=0
for hex_pt in ${comp_list[@]}
do
unpack_cmd=${hex_pt}
LOC1=`grep -P -a -b --only-matching "'${comp_pt_list[hex_pt]}'" $1 | tail -1 | cut -d: -f 1`
if [ $LOC1 ]
then
	break
else
	let hex_pt++
fi
done

LOC=$LOC1
if [ $LOC ]
then
	echo "$unpack_cmd compression detected"
	echo "Unpacking zImage"
	case "$unpack_cmd" in
		"xz" ) opt="-dc" ;;
		"lzop" ) opt="-do" ;;
		"lz4" ) opt="-d" ;;
		"gzip" ) opt="-dc" ;;
	esac
	dd if=$1 bs=$LOC1 skip=1 | $unpack_cmd $opt > kernel.Image
	if [ -e kernel.Image ]
	then
		echo "DONE unpacking zImage"
		echo "Grabbing addresses"
		~/android/scripts/kallsymsprint.x86 kernel.Image > kallsyms.txt

		cat kallsyms.txt | grep " prepare_kernel_cred" >> addresses.txt
		cat kallsyms.txt | grep " commit_creds" >> addresses.txt
		cat kallsyms.txt | grep " remap_pfn_range" >> addresses.txt
		cat kallsyms.txt | grep " vmalloc_exec" >> addresses.txt

		echo "Disassembling kernel for specific functions"
		~/android/scripts/arm7-dasm kernel.Image c0008000 pty_init kallsyms.txt > pty_init.dasm
		~/android/scripts/arm7-dasm kernel.Image c0008000 unix98_pty_init kallsyms.txt >> pty_init.dasm
		~/android/scripts/arm7-dasm kernel.Image c0008000 sw_perf_event_destroy kallsyms.txt > sw_perf_event_destroy.dasm

		echo "searching for ptmx_fops"
		ADDR_PTMX_FOPS=`~/android/scripts/get-ptmx_fops pty_init.dasm`
		echo "$ADDR_PTMX_FOPS = (hexdec addition)    ptmx_fops"  >> addresses.txt

		echo "searching for perf_swevent_enabled"
		ADDR_SWPREF=`~/android/scripts/get-perf_swevent_enabled sw_perf_event_destroy.dasm`
		echo "$ADDR_SWPREF perf_swevent_enabled"  >> addresses.txt

	else
		echo "ERROR! unpacking zImage"
	fi
else
	echo "ERROR! zImage has different compression"
fi
